In [1]:
import sys
from pathlib import Path
from os.path  import join
from src.config import DATA_DIR, CONFIG_DIR, MODELS_DIR
from omegaconf import OmegaConf
from src.external.hptr.src.data_modules.agent_centric import AgentCentricPreProcessing
from src.external.hptr.src.data_modules.ac_global import AgentCentricGlobal
from src.mimolm import InputProjections, EarlyFusionEncoder, MotionDecoder
import torch
import torch.nn.functional as F
import lightning as pl
import datetime
from src.modeling.modules.lm_utils import tokenize_motion

# Add the project root to sys.path
project_root = Path().resolve().parent  # Adjust as needed to point to the root folder
sys.path.append(str(project_root))

print(Path.cwd())  # Check if the path is added

2025-03-10 16:23:59.590 | INFO     | src.config:<module>:11 - PROJ_ROOT path is: /home/harshavardhan-patil/Work/Projects/mimolm


/home/harshavardhan-patil/Work/Projects/mimolm/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


/home/harshavardhan-patil/Work/Projects/mimolm/notebooks


In [2]:
from src.external.hptr.src.data_modules.data_h5_av2 import DataH5av2
from src.mimolm import MimoLM
from src.modeling.modules.lm_utils import interpolate_trajectory, cluster_rollouts, non_maximum_suppression

torch.set_printoptions(sci_mode=False)
data_module = DataH5av2(DATA_DIR
                        , batch_size=2)
data_module.setup(stage="fit")
train_loader = data_module.train_dataloader()
val_loader = data_module.val_dataloader()

model = MimoLM.load_from_checkpoint(MODELS_DIR / "epoch=7-step=3576.ckpt"#"epoch=13-step=6258.ckpt"
    ,data_size=data_module.tensor_size_val)

trainer = pl.Trainer(fast_dev_run=1)
output = trainer.fit(model=model, train_dataloaders=train_loader, val_dataloaders=val_loader)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Running in `fast_dev_run` mode: will run the requested loop using 1 batch(es). Logging and checkpointing is suppressed.
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type               | Params | Mode 
-----------------------------------------------------------------
0 | preprocessor      | Sequential         | 0      | train
1 | input_projections | InputProjections   | 247 K  | train
2 | encoder           | EarlyFusionEncoder | 2.3 M  | train
3 | decoder           | MotionDecoder   

Epoch 0: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, train_loss_step=3.480]torch.Size([2, 8, 60, 2])
torch.Size([2, 8, 60, 2])
torch.Size([1, 1, 60, 2])
torch.Size([1, 60, 2])
torch.Size([1, 1, 60, 2])
torch.Size([1, 60, 2])
Epoch 0: 100%|██████████| 1/1 [00:01<00:00,  0.66it/s, train_loss_step=3.480, val_loss_step=10.20, MinADE_step=2.630, MinFDE_step=4.800, val_loss_epoch=10.20, MinADE_epoch=2.630, MinFDE_epoch=4.800, train_loss_epoch=3.480]

`Trainer.fit` stopped: `max_steps=1` reached.


Epoch 0: 100%|██████████| 1/1 [00:01<00:00,  0.66it/s, train_loss_step=3.480, val_loss_step=10.20, MinADE_step=2.630, MinFDE_step=4.800, val_loss_epoch=10.20, MinADE_epoch=2.630, MinFDE_epoch=4.800, train_loss_epoch=3.480]


In [2]:
from src.external.hptr.src.data_modules.data_h5_av2 import DataH5av2
from src.mimolm import MimoLM
from src.modeling.modules.lm_utils import interpolate_trajectory, cluster_rollouts, non_maximum_suppression

torch.set_printoptions(sci_mode=False)
data_module = DataH5av2(DATA_DIR
                        , batch_size=2)
data_module.setup(stage="validate")
val_loader = data_module.val_dataloader()

model = MimoLM.load_from_checkpoint(MODELS_DIR / "epoch=7-step=3576.ckpt"#"epoch=13-step=6258.ckpt"
    ,data_size=data_module.tensor_size_val
                , n_rollouts = 12)

trainer = pl.Trainer(fast_dev_run=100)
output = trainer.test(model=model, dataloaders=val_loader)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Running in `fast_dev_run` mode: will run the requested loop using 100 batch(es). Logging and checkpointing is suppressed.
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Testing DataLoader 0: 100%|██████████| 100/100 [00:39<00:00,  2.55it/s]


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│     BrierMinFDE_epoch     │    0.46925631165504456    │
│       MinADE_epoch        │    3.4804694652557373     │
│       MinFDE_epoch        │    7.1179962158203125     │
└───────────────────────────┴───────────────────────────┘

In [2]:
from src.external.hptr.src.data_modules.data_h5_av2 import DataH5av2
from src.mimolm import MimoLM
from src.modeling.modules.lm_utils import interpolate_trajectory, cluster_rollouts, non_maximum_suppression
#43648
torch.set_printoptions(sci_mode=False)
data_module = DataH5av2(DATA_DIR
                        , batch_size=2)
data_module.setup(stage="test")
test_loader = data_module.test_dataloader()

model = MimoLM.load_from_checkpoint(MODELS_DIR / "epoch=7-step=3576.ckpt"#"epoch=13-step=6258.ckpt"
    ,data_size=data_module.tensor_size_val
                , n_rollouts = 12)

trainer = pl.Trainer(fast_dev_run=10)
trainer.predict(model=model, dataloaders=test_loader)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Running in `fast_dev_run` mode: will run the requested loop using 10 batch(es). Logging and checkpointing is suppressed.
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0:  10%|█         | 1/10 [00:00<00:07,  1.19it/s]

/home/harshavardhan-patil/Work/Projects/mimolm/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/prediction_loop.py:257: predict returned None if it was on purpose, ignore this warning...


Predicting DataLoader 0: 100%|██████████| 10/10 [00:04<00:00,  2.41it/s]


[None, None, None, None, None, None, None, None, None, None]

In [3]:
len(model.predictions.keys())

20

In [3]:
from av2.datasets.motion_forecasting.eval.submission import ChallengeSubmission

ChallengeSubmission(model.predictions).to_parquet('mm.parquet')

In [4]:
import pandas as pd

submission_df = pd.read_parquet("mm.parquet")
len(submission_df['scenario_id'].unique())

2

In [5]:
submission_df

,scenario_id,track_id,probability,predicted_trajectory_x,predicted_trajectory_y
0,0000b329-f890-4c2b-93f2-7e2413d4ca5b,"tensor([43648], device='cuda:0')",0.833333,"[35.50846401626543, 35.50846401626543, 35.5084...","[-38.773384020744565, -38.773384020744565, -38..."
1,0000b329-f890-4c2b-93f2-7e2413d4ca5b,"tensor([43648], device='cuda:0')",0.166667,"[35.50846401664778, 35.50846401664778, 35.5084...","[-38.77338402047878, -38.77338402047878, -38.7..."
2,0000b329-f890-4c2b-93f2-7e2413d4ca5b,"tensor([43648], device='cuda:0')",0.000000,"[34.693145751953125, 34.693145751953125, 34.69...","[-37.611305236816406, -37.611305236816406, -37..."
3,0000b329-f890-4c2b-93f2-7e2413d4ca5b,"tensor([43648], device='cuda:0')",0.000000,"[34.693145751953125, 34.693145751953125, 34.69...","[-37.611305236816406, -37.611305236816406, -37..."
4,0000b329-f890-4c2b-93f2-7e2413d4ca5b,"tensor([43648], device='cuda:0')",0.000000,"[34.693145751953125, 34.693145751953125, 34.69...","[-37.611305236816406, -37.611305236816406, -37..."
5,0000b329-f890-4c2b-93f2-7e2413d4ca5b,"tensor([43648], device='cuda:0')",0.000000,"[34.693145751953125, 34.693145751953125, 34.69...","[-37.611305236816406, -37.611305236816406, -37..."
6,0008c251-e9b0-4708-b762-b15cb6effc27,"tensor([134328], device='cuda:0')",0.500000,"[-15.490322773776972, -15.490322773776972, -15...","[-4.766046429157457, -4.766046429157457, -4.76..."
7,0008c251-e9b0-4708-b762-b15cb6effc27,"tensor([134328], device='cuda:0')",0.166667,"[-15.490322773776972, -15.490322773776972, -15...","[-4.766046429157457, -4.766046429157457, -4.76..."
8,0008c251-e9b0-4708-b762-b15cb6effc27,"tensor([134328], device='cuda:0')",0.250000,"[-15.595402791442481, -15.595402791442481, -15...","[-4.668909023348444, -4.668909023348444, -4.66..."
9,0008c251-e9b0-4708-b762-b15cb6effc27,"tensor([134328], device='cuda:0')",0.083333,"[-15.490322773776972, -15.490322773776972, -15...","[-4.766046429157457, -4.766046429157457, -4.76..."


In [4]:
motion_tokens = torch.cat((batch["ac/target_pos"], batch["gt/pos"][:, :, ::model.decoder.sampling_step,]), dim = -2).to('cpu')
actuals, _ = tokenize_motion(motion_tokens,
    model.decoder.pos_bins, 
    model.decoder.verlet_wrapper, 
    model.decoder.n_verlet_steps,
    model.decoder.max_delta)
actuals[~torch.cat([batch["input/target_valid"], batch["gt/valid"][:, :, ::model.decoder.sampling_step,]], dim=-1)] = 169
actuals

tensor([[[ 57,  57,  87, 150, 121, 107, 111,  22,   7, 121,  58, 122,  70,  86,
           86,  58,   6, 159, 156, 149, 129, 119],
         [168, 168, 139,  71,  83,  82,  69,  83,  83,  70,  69,  82,  70,  71,
           73, 100, 101, 101, 100,  98,  95,  95],
         [168, 168, 124,  57,  57,  19,   6,   0,  28,  57,  61,  62,  65,  68,
           63, 128,  44,   4, 158, 114,  98, 133],
         [168, 168, 141,  60,  68,  81,  57,  70,  71,  86,  68,  74,  74,  65,
           67,  67,  82,  76,  34,  56, 113,  91],
         [166, 166, 139, 110,  97, 106, 105,  97,  90,  77,  55,  41,  45,  56,
           53,  89,   7,  54, 156, 162,  38,  61],
         [169, 169, 169,  12, 116,  64,   0,  13, 139,  49, 100, 120, 130, 169,
          169, 169, 169, 169, 169, 169, 169, 169],
         [169, 169, 169, 169,  12, 115,  28,  43,  59,   1,  51,  89,  91, 134,
          160, 157, 159, 129,  12, 169, 169, 169],
         [ 99,  99,   0, 160, 168,  10,   4, 161, 111,  57, 121, 161,  70,  72,
   

In [11]:
pred_tokens = tokenize_motion(prediction[0].unsqueeze(0),
    model.decoder.pos_bins, 
    model.decoder.verlet_wrapper, 
    model.decoder.n_verlet_steps,
    model.decoder.max_delta)
pred_tokens

(tensor([[[ 84,  84,  84,  84,  84, 164,   4,  84,  84,  84, 168,   0,  84,  84,
            84, 168,   1,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,  84,
            84,  84, 168,   0,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,
            84,  84,  84, 168,   0,  84,  84,  84, 168,   0,  84,  84,  84, 168,
             0,  84,  84,  84],
          [ 84,  84,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,  84,  84,
            84, 168,   0,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,  84,
            84,  84, 168,   0,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,
            84,  84,  84, 168,   0,  84,  84,  84, 168,   0,  84,  84,  84, 168,
             0,  84,  84,  84],
          [ 84,  84,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,  84,  84,
            84, 168,   0,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,  84,
            84,  84, 168,   0,  84,  84,  84, 168,   0,  84,  84,  84, 168,   0,
            84,  84,  84, 168,   0,  84,  84,

In [11]:
break

SyntaxError: 'break' outside loop (668683560.py, line 1)

In [ ]:
import torch

token = torch.randint(100, (2, 3, 5, 1)) / 100.
token

tensor([[[[0.0100],
          [0.3600],
          [0.1000],
          [0.6700],
          [0.1900]],

         [[0.0700],
          [0.4900],
          [0.5600],
          [0.7900],
          [0.5100]],

         [[0.0700],
          [0.9600],
          [0.8500],
          [0.8000],
          [0.8800]]],


        [[[0.8700],
          [0.3300],
          [0.6800],
          [0.7200],
          [0.4500]],

         [[0.8100],
          [0.9300],
          [0.5300],
          [0.9100],
          [0.6600]],

         [[0.8000],
          [0.9000],
          [0.9000],
          [0.1000],
          [0.9500]]]])

In [ ]:
motion_embeddings = token.flatten(1,2)
print(motion_embeddings.shape)
print(motion_embeddings)
query = motion_embeddings

torch.Size([2, 15, 1])
tensor([[[0.0100],
         [0.3600],
         [0.1000],
         [0.6700],
         [0.1900],
         [0.0700],
         [0.4900],
         [0.5600],
         [0.7900],
         [0.5100],
         [0.0700],
         [0.9600],
         [0.8500],
         [0.8000],
         [0.8800]],

        [[0.8700],
         [0.3300],
         [0.6800],
         [0.7200],
         [0.4500],
         [0.8100],
         [0.9300],
         [0.5300],
         [0.9100],
         [0.6600],
         [0.8000],
         [0.9000],
         [0.9000],
         [0.1000],
         [0.9500]]])


In [ ]:
from src.modeling.modules.lm_utils import get_attention_mask

attn_mask = get_attention_mask(5, query.shape[1])
print(attn_mask.shape)
print(attn_mask)

torch.Size([15, 15])
tensor([[False,  True,  True,  True,  True, False,  True,  True,  True,  True,
         False,  True,  True,  True,  True],
        [False, False,  True,  True,  True, False, False,  True,  True,  True,
         False, False,  True,  True,  True],
        [False, False, False,  True,  True, False, False, False,  True,  True,
         False, False, False,  True,  True],
        [False, False, False, False,  True, False, False, False, False,  True,
         False, False, False, False,  True],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False],
        [False,  True,  True,  True,  True, False,  True,  True,  True,  True,
         False,  True,  True,  True,  True],
        [False, False,  True,  True,  True, False, False,  True,  True,  True,
         False, False,  True,  True,  True],
        [False, False, False,  True,  True, False, False, False,  True,  True,
         False, False, False,  T

In [ ]:
padding_mask = torch.randint(0, 2, [2, 3, 5]).flatten(1, -1)
print(padding_mask.shape)
print(padding_mask)

torch.Size([2, 15])
tensor([[0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0],
        [1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0]])


In [ ]:
import torch.nn as nn

self_attn = nn.MultiheadAttention(embed_dim = 1, num_heads = 1, batch_first=True)

In [ ]:
attn_out_1, _ = self_attn(query, query, query, attn_mask=attn_mask, key_padding_mask = padding_mask.bool())
print(attn_out_1.shape)
print(attn_out_1)

torch.Size([2, 15, 1])
tensor([[[0.0063],
         [0.3032],
         [0.2576],
         [0.3483],
         [0.3709],
         [0.0063],
         [0.3017],
         [0.2541],
         [0.3476],
         [0.3693],
         [0.0063],
         [0.2962],
         [0.2519],
         [0.3475],
         [0.3673]],

        [[   nan],
         [0.2092],
         [0.4017],
         [0.3813],
         [0.4136],
         [   nan],
         [0.2092],
         [0.4021],
         [0.3804],
         [0.4126],
         [   nan],
         [0.2092],
         [0.4010],
         [0.3841],
         [0.4112]]], grad_fn=<TransposeBackward0>)


In [ ]:
attn_out_2 = attn_out_1.unflatten(dim=1, sizes=(3, 5)).flatten(0, 1)
print(attn_out_2.shape)
print(attn_out_2)

torch.Size([6, 5, 1])
tensor([[[0.0063],
         [0.3032],
         [0.2576],
         [0.3483],
         [0.3709]],

        [[0.0063],
         [0.3017],
         [0.2541],
         [0.3476],
         [0.3693]],

        [[0.0063],
         [0.2962],
         [0.2519],
         [0.3475],
         [0.3673]],

        [[   nan],
         [0.2092],
         [0.4017],
         [0.3813],
         [0.4136]],

        [[   nan],
         [0.2092],
         [0.4021],
         [0.3804],
         [0.4126]],

        [[   nan],
         [0.2092],
         [0.4010],
         [0.3841],
         [0.4112]]], grad_fn=<UnsafeViewBackward0>)


In [ ]:
fused_emb = torch.randint(100, (6, 10, 1)) / 100.
fused_emb

tensor([[[0.7100],
         [0.2300],
         [0.3800],
         [0.4900],
         [0.5300],
         [0.9300],
         [0.0900],
         [0.3300],
         [0.6300],
         [0.6800]],

        [[0.5500],
         [0.7000],
         [0.2400],
         [0.9500],
         [0.3100],
         [0.1500],
         [0.8400],
         [0.3400],
         [0.8100],
         [0.1000]],

        [[0.7500],
         [0.5600],
         [0.1000],
         [0.6200],
         [0.4000],
         [0.1800],
         [0.6400],
         [0.3500],
         [0.2100],
         [0.0500]],

        [[0.2600],
         [0.2200],
         [0.0600],
         [0.0100],
         [0.8800],
         [0.5100],
         [0.4800],
         [0.9100],
         [0.5800],
         [0.2500]],

        [[0.7500],
         [0.2300],
         [0.4900],
         [0.9500],
         [0.4800],
         [0.4800],
         [0.6900],
         [0.4100],
         [0.2800],
         [0.1400]],

        [[0.9000],
         [0.2100],
  

In [ ]:
cross_attn = nn.MultiheadAttention(embed_dim = 1, num_heads = 1, batch_first=True)

In [ ]:
query, _ = cross_attn(attn_out_2, fused_emb, fused_emb)
print(query.shape)
print(query)

torch.Size([6, 5, 1])
tensor([[[0.1355],
         [0.1363],
         [0.1362],
         [0.1364],
         [0.1365]],

        [[0.1352],
         [0.1364],
         [0.1362],
         [0.1366],
         [0.1367]],

        [[0.1046],
         [0.1054],
         [0.1052],
         [0.1055],
         [0.1055]],

        [[   nan],
         [0.1136],
         [0.1144],
         [0.1143],
         [0.1144]],

        [[   nan],
         [0.1333],
         [0.1338],
         [0.1338],
         [0.1338]],

        [[   nan],
         [0.1272],
         [0.1281],
         [0.1280],
         [0.1281]]], grad_fn=<TransposeBackward0>)


In [ ]:
query = query.unflatten(dim=0, sizes=(2, 3)).flatten(1, 2)
print(query.shape)
print(query)

torch.Size([2, 15, 1])
tensor([[[0.1355],
         [0.1363],
         [0.1362],
         [0.1364],
         [0.1365],
         [0.1352],
         [0.1364],
         [0.1362],
         [0.1366],
         [0.1367],
         [0.1046],
         [0.1054],
         [0.1052],
         [0.1055],
         [0.1055]],

        [[   nan],
         [0.1136],
         [0.1144],
         [0.1143],
         [0.1144],
         [   nan],
         [0.1333],
         [0.1338],
         [0.1338],
         [0.1338],
         [   nan],
         [0.1272],
         [0.1281],
         [0.1280],
         [0.1281]]], grad_fn=<UnsafeViewBackward0>)


In [ ]:
target_valid = torch.randint(0, 2, [2, 8, 25])
if target_valid.shape[-1] != 55:
    target_valid = torch.cat([target_valid, torch.ones([2, 8, 55 - target_valid.shape[-1]])], dim=-1)
torch.randn([2, 8, 55, 1])[~target_valid.bool()].shape

torch.Size([201, 1])